name: Keep Alive

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit
        run: curl -s https://budget-app-ypsxgdp6zsfxxfuuxgepks.streamlit.app/

      - name: Ping Supabase
        run: curl -s https://pskfhdscxuauqxsmfrjm.supabase.co/health
